### PR TITLE
Add gifs functionality... again

### PR DESCRIPTION
**Pull request by pabloriutort**
In this PR I want to do the same thing with a random animal image but with a gif instead.
The last commit has the needed functions to get a gif or to return the current url. In the gif's case the function just returns the gif's url but in the animals(...) function the image is downloaded.

Does the animals(...) function needs to be modified for downloading one thing or the other? Any ideas?

### CODE REVIEW

**Comment by Nosk14** [comment]
You should change the animals function to randomly choose a gif or an image. Maybe you just need to change the first parameter of `urlretrieve("http://lorempixel.com/400/300/animals",img_name)` for a variable containing the gif url or the image jpg url.

**Comment by pabloriutort** [comment]
Hello! My PR is ready. Could somebody download it and see if it works properly?
If it does, please merge and close this branch.

**Comment by Nosk14** [comment]
There is a problem with this.
> Traceback (most recent call last):
>   File "/usr/local/engendro-bot/main.py", line 3, in <module>
>     from handlers import animals, reverse, botinfo, globalHandler
>   File "/usr/local/engendro-bot/handlers/animals.py", line 4, in <module>
>     from requests import get
> ImportError: No module named 'requests'
The server uses only Python3. Look for a module in the native library of python3  with the same functionality or add requests module to the requirements file

**Comment by pabloriutort** [comment]
Ok, then unmerge the branch until it's fixed

**Pull request merged**
