### PR TITLE
Set a debugger mode in environment

### PR DESCRIPTION
**Pull request by pabloriutort**
Search for a DEBUG index in environment (or .env file).
If DEBUG=1 then change the logging mode to DEBUG

### CODE REVIEW

**Comment by pabloriutort** [comment]
Using this approach we could also define the entire scope of the bot logging. For instance the environment variable could store which level of verbosity we want in the logs, something like: 
`LOGGING=['INFO' | 'WARNING' | 'DEBUG']`

**Comment by Nosk14** [comment]
LGTM

**Comment by pabloriutort** [comment]
@Nosk14 have you tested?

**Comment by Nosk14** [comment]
No 💃 
I will test it later

**Comment by Nosk14** [comment]
Tested and it works fine

**Pull request merged**
