### PR TITLE
Rolladice

### PR DESCRIPTION
**Pull request by Nosk14**

### CODE REVIEW

**Comment by pabloriutort** [comment]
Hello! To review this the proper way I'm going to need the bot token :smiling_imp:

**Comment by marc-ferrer** [comment]
LGTM

**Comment by Nosk14** [comment]
@pabloriutort I thought you have the token. Anyway, you can use any bot token to test it or I can send you the token of Engendro  by mail or something

**Comment by pabloriutort** [comment]
Did not know I could use any token, in that case problem solved. I'll test
this PR.

2017-03-20 16:53 GMT+01:00 Carlos Lucas <notifications@github.com>:

**Comment by pabloriutort** [comment]
Test results don't look good for this new command:
test

Following the docs of the roll_command, after executing `/roll [0-9]+d[0-9]+` it just replies the same input.

**Comment by Nosk14** [comment]
@pabloriutort problem fixed. It was returning the wrong string :P

**Pull request merged**
